import { IAlign } from "./types";
export declare const SUPPORT_COMPUTEDSTYLE: boolean;
export declare const SUPPORT_ADDEVENTLISTENER: boolean;
export declare const SUPPORT_PASSIVE: boolean;
export declare const IS_IE: boolean;
export declare const IS_IOS: boolean;
export declare const IS_ANDROID2: boolean;
export declare const CONTAINER_CLASSNAME = "_eg-infinitegrid-container_";
export declare const IGNORE_CLASSNAME = "_eg-infinitegrid-ignore_";
export declare const TRANSITION_NAME = "_INFINITEGRID_TRANSITION";
export declare const APPEND: boolean;
export declare const PREPEND: boolean;
export declare const VERTICAL = "vertical";
export declare const HORIZONTAL = "horizontal";
export declare const CACHE: boolean;
export declare const NO_CACHE: boolean;
export declare const TRUSTED: boolean;
export declare const NO_TRUSTED: boolean;
export declare const MULTI: boolean;
export declare const SINGLE: boolean;
export declare const DUMMY_POSITION = -100000;
export declare const GROUPKEY_ATT = "data-groupkey";
export declare const DEFAULT_OPTIONS: {
    horizontal: boolean;
    margin: number;
};
export declare const agent: string;
export declare const isMobile: boolean;
export declare const ALIGN: IAlign;
export declare const IDLE = 0;
export declare const LOADING_APPEND = 1;
export declare const LOADING_PREPEND = 2;
export declare const PROCESSING = 4;
export declare const WEBKIT_VERSION: number;
export declare const DEFENSE_BROWSER: boolean;
export declare const TRANSFORM: "transform", TRANSITION: "transition", TRANSITION_END: "transitionend";
