import Component from "@egjs/component";
import { IInfiniteGridItem, IItemManagerStatus } from "./ItemManager";
import { IDOMRendererStatus } from "./DOMRenderer";
import { IWatchStatus } from "./Watcher";
import { IInfiniteStatus } from "./Infinite";
import { IJQuery, ILayout, StyleType } from "./types";
export interface IInfiniteGridOptions {
    itemSelector: string;
    isOverflowScroll: boolean;
    threshold: number;
    isEqualSize: boolean;
    isConstantSize: boolean;
    useRecycle: boolean;
    horizontal: boolean;
    transitionDuration: number;
    useFit: boolean;
    attributePrefix: string;
}
export interface IInfiniteGridStatus {
    _status: {
        processingStatus: number;
        loadingSize: number;
        loadingStyle: StyleType;
    };
    _items: IItemManagerStatus;
    _renderer: IDOMRendererStatus;
    _watcher: IWatchStatus;
    _infinite: IInfiniteStatus;
}
declare class InfiniteGrid extends Component {
    static VERSION: string;
    options: IInfiniteGridOptions;
    private _loadingBar;
    private _items;
    private _renderer;
    private _manager;
    private _watcher;
    private _infinite;
    private _status;
    constructor(element: HTMLElement | string | IJQuery, options?: Partial<IInfiniteGridOptions>);
    append(elements: HTMLElement[] | IJQuery | string[] | string, groupKey?: string | number): this;
    prepend(elements: HTMLElement[] | IJQuery | string[] | string, groupKey?: string | number): this;
    setLayout(LayoutKlass: ILayout | (new (...args: any[]) => ILayout), options?: {}): this;
    getItems(includeCached?: boolean): IInfiniteGridItem[];
    layout(isRelayout?: boolean): this;
    remove(element: HTMLElement, isLayout?: boolean): IInfiniteGridItem[];
    getGroupKeys(includeCached?: boolean): (string | number)[];
    getStatus(startKey?: string | number, endKey?: string | number): IInfiniteGridStatus;
    setStatus(status: IInfiniteGridStatus, applyScrollPos?: boolean): this;
    clear(): this;
    setLoadingBar(userLoadingBar?: {
        append?: string | HTMLElement;
        prepepnd?: string | HTMLElement;
    } | string): this;
    isProcessing(): boolean;
    getLoadingBar(isAppend?: boolean): HTMLElement;
    startLoading(isAppend?: boolean, userStyle?: StyleType): this;
    endLoading(userStyle?: StyleType): this;
    getItem(groupIndex?: number, itemIndex?: number): IInfiniteGridItem;
    updateItem(groupIndex?: number, itemIndex?: number): this;
    updateItems(): this;
    moveTo(index?: number, itemIndex?: number): this;
    destroy(): void;
    private _setContainerSize;
    private _appendLoadingBar;
    private _setSize;
    private _fitItems;
    private _fit;
    private _getEdgeValue;
    private _isProcessing;
    private _isLoading;
    private _getLoadingStatus;
    private _process;
    private _insert;
    private _recycle;
    private _renderLoading;
    private _updateItem;
    private _setScrollPos;
    private _scrollTo;
    private _onImageError;
    private _postCache;
    private _postLayout;
    private _requestAppend;
    private _requestPrepend;
    private _onResize;
    private _onCheck;
    private _onLayoutComplete;
    private _reset;
}
export default InfiniteGrid;
